name: Deploy to AWS Lambda (Probot App)

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
  push:
    branches:
      - '!release-branch'
      - master
      - 1.*
      - develop
      - MOSIP*
      - release*

jobs:
  deploy-to-lambda:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Install dependencies
      run: |
        cd notifier-slackbot && npm ci
      
    - name: Zip deployment package
      run: |
        cd notifier-slackbot
        zip -q -r lambda-deployment.zip index.js node_modules package-lock.json package.json
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        mask-aws-account-id: true
    
    - name: Deploy to Lambda
      run: |
        cd notifier-slackbot
        aws lambda update-function-code \
          --function-name probot-app \
          --zip-file fileb://lambda-deployment.zip \
          --no-cli-pager \
          --query 'LastUpdateStatus' \
          --output text